---
driver:
  name: digitalocean
driver_config:
  ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>

provisioner:
  name: chef_solo

platforms:
  - name: centos-6-5-x64

suites:
  - name: default
    run_list:
      - recipe[opt-gnu-parallel::default]
    attributes:
  - name: modulefile
    run_list:
      - recipe[opt-gnu-parallel::modulefile]
    attributes:
